apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-librairies
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-librairies
  template:
    metadata:
      labels:
        app: my-librairies
    spec:
      containers:
        - name: my-librairies
          image: mylibrairies
          ports:
            - containerPort: 8088
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: my-librairies
  labels:
    app: my-librairies
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  selector:
    app: my-librairies