apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-librairies
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-librairies
  template:
    metadata:
      labels:
        app: my-librairies
    spec:
      containers:
        - name: my-librairies
          image: mylibrairies
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: my-librairies
  labels:
    app: my-librairies
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: my-librairies
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  name: my-librairies
  namespace: dev
spec:
  rules:
    - host: mylibrairies.sitcluster.eu-de.containers.appdomain.cloud
      http:
        paths:
          - path: /
            backend:
              serviceName: my-librairies
              servicePort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-librairies
  namespace: dev
data:
  application.properties: |
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.datasource.url=jdbc:postgresql://b8a37426-5db1-4789-8cc7-f81692070b29.blrv234f085n1l00bhrg.databases.appdomain.cloud:32722/ibmclouddb?ssl=true&sslmode=require&sslfactory=org.postgresql.ssl.NonValidatingFactory
    spring.datasource.username=ibm_cloud_7ab5f8b9_021b_45d7_b73b_8dcc8dae9fe0
    spring.datasource.password=633f0f5bf98e7aa16f75bcf992f1b85294b0e5d087596bb05d7a4ecb8903f076
    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
    spring.h2.console.enabled=false
    spring.jpa.show-sql=true
    spring.jpa.hibernate.ddl-auto=create
    spring.jackson.serialization.fail-on-empty-beans=false